<?php

/*
  Plugin Name: Logs Display
  Plugin URI: http://web-startup.fr/wp-logs-display/
  Description: Capture and display logs generated by your system. The logs are displayed by a widget added to the dashboard.
  Version: 1.3.1
  Author: Steeve Lefebvre
  Author URI: web-startup.fr
  License: GPLv2 or later
  License URI: http://www.gnu.org/licenses/gpl-2.0.html
  Text Domain: lodi
  Contributors: webstartup, Benoti, citoyensdebout

  ------------------------------------------------------------------------------
  Note pour les anglophones : quand un code commenté en anglais me plait
  et qu'aucune traduction n'est disponible, je dois me démerder.
  Merci de bien vouloir me rendre la pareille :-þ
 */

defined('ABSPATH') or exit();

__('Logs display', 'lodi');
__('Capture and display logs generated by your system. The logs are displayed by a widget added to the dashboard.', 'lodi');


/**
 * GRP support
 */
if (!is_admin()):
    $GROUPER_LOGS_DISPLAY = false;
else:
    if ('true' === get_option('slwsu_is_active_grouper', 'false')):
        if (!class_exists('slwsu_grouper_init')):
            require_once WP_PLUGIN_DIR . '/grouper/init.php';
        endif;
        $GROUPER_LOGS_DISPLAY = new slwsu_grouper_init(get_option('slwsu_logs_display_grouper'), '4.4', '5.5');
    endif;
endif;

/**
 * Entrée du plugin
 */
class slwsu_logs_display {

    public function __construct() {

        // Hook
        register_activation_hook(__FILE__, array($this, 'activate'));
        register_deactivation_hook(__FILE__, array($this, 'deactivate'));
        add_action('plugins_loaded', array($this, 'text_domain'));
        add_filter('plugin_action_links_' . plugin_basename(__FILE__), array($this, 'setting_links'));

        // Grouper 
        global $GROUPER_LOGS_DISPLAY;
        if (is_object($GROUPER_LOGS_DISPLAY)):
            if (false === $GROUPER_LOGS_DISPLAY->wp_status or false === $GROUPER_LOGS_DISPLAY->php_status):
                add_action('admin_init', array($this, 'deactivate_auto'));
            endif;
        endif;

        // Plugin
        $this->plugin();
    }

    /**
     * Plugin
     */
    private function plugin() {
        if (false !== get_option('bfsl_logs-display_widget')):
            $this->bfsl_maj();
        endif;
        
        include_once plugin_dir_path(__FILE__) . 'plugin/init.php';
        new slwsu_logs_display_plugin_init();
    }

    /**
     * 
     */
    public function bfsl_maj() {
        delete_option('bfsl_logs-display_widget');
        delete_transient('bfsl_logs-display_options');
        
        include_once plugin_dir_path(__FILE__) . 'plugin/options.php';
        $options = slwsu_logs_display_options::options();
        foreach ($options as $k => $v):
            add_option('slwsu_logs_display_' . $k, $v);
        endforeach;
    }

    /**
     * Languages
     */
    public static function text_domain() {
        load_plugin_textdomain('lodi', false, dirname(plugin_basename(__FILE__)) . '/languages');
    }

    /**
     * Liens
     */
    public function setting_links($aLinks) {
        $links[] = '<a href="https://web-startup.fr/logs-display/">' . __('Page', 'lodi') . '</a>';
        $links[] = '<a href="' . admin_url('admin.php?page=logs-display') . '">' . __('Settings', 'lodi') . '</a>';
        return array_merge($links, $aLinks);
    }

    /**
     * Activation
     */
    public static function activate() {
        $option = slwsu_logs_display::options();
        foreach ($option as $k => $v):
            add_option($k, $v);
        endforeach;
        unset($k, $v);
    }

    /**
     * Désactivation
     */
    public static function deactivate() {
        if ('true' === get_option('slwsu_logs_display_delete_options', 'false')):
            $option = slwsu_logs_display::options();
            foreach ($option as $k => $v):
                delete_option($k);
            endforeach;
            unset($k, $v);
        endif;
    }

    /**
     * Options
     */
    public static function options() {
        include_once plugin_dir_path(__FILE__) . 'plugin/options.php';
        return slwsu_logs_display_options::get_options();
    }

    /**
     * Désactivation automatique
     */
    public static function deactivate_auto() {
// On désactive le plugin
        deactivate_plugins(plugin_basename(__FILE__));
    }

}

/**
 * 
 */
new slwsu_logs_display();